name: Auto Commit Ranking

on:
  push:
    paths:
      - 'source/txt/ranking.txt'

jobs:
  commit-ranking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git add source/txt/ranking.txt
          git commit -m "Update ranking.txt from PHP submission" || echo "No changes to commit"
          git push
